[workspace]
authors = ["Seongwoo Lim <252972047+seongwoolim-ineeji@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "backend"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
fastapi = ">=0.129.0,<0.130"

[environments]
api = ["api"]
api-ci = ["ci"]

[feature.api.dependencies]
uvicorn = "*"
ruff = "*"

[feature.ci.dependencies]
pytest = "*"
