name: cd-gcp

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  GAR_LOCATION: asia-northeast3
  CLOUD_RUN_REGION: asia-northeast3

  GAR_REPOSITORY: delpoyment-by-github-action
  CLOUD_RUN_SERVICE: delpoyment-by-github-action-api
  IMAGE_NAME: api

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev" --quiet

      - name: Set image variables
        run: |
          IMAGE_BASE="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}"
          echo "IMAGE_SHA=${IMAGE_BASE}:${GITHUB_SHA}" >> $GITHUB_ENV
          echo "IMAGE_LATEST=${IMAGE_BASE}:latest" >> $GITHUB_ENV

      - name: Build and push (GAR)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/api/Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE_SHA }}
            ${{ env.IMAGE_LATEST }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ env.CLOUD_RUN_SERVICE }}
          region: ${{ env.CLOUD_RUN_REGION }}
          image: ${{ env.IMAGE_SHA }}
          flags: --allow-unauthenticated
